// This file is auto-generated by @hey-api/openapi-ts

export const AssignmentMethodSchema = {
    type: 'string',
    enum: [
        'geo_nearest',
        'geo_fallback_astana',
        'geo_fallback_almaty',
        'round_robin',
        'skipped_spam',
        'no_eligible_manager'
    ],
    title: 'AssignmentMethod',
    description: 'How the ticket was routed (for audit traceability).'
} as const;

export const BackgroundTaskReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ticket_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ticket Id'
        },
        task_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Id'
        },
        task_name: {
            type: 'string',
            title: 'Task Name'
        },
        status: {
            $ref: '#/components/schemas/TaskStatus'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        payload: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payload'
        }
    },
    type: 'object',
    required: [
        'created_at',
        'id',
        'task_name',
        'status'
    ],
    title: 'BackgroundTaskRead',
    description: 'Schema for reading a BackgroundTask.'
} as const;

export const Body_ingest_csv_files_api_v1_fire_ingest_postSchema = {
    properties: {
        business_units: {
            type: 'string',
            format: 'binary',
            title: 'Business Units',
            description: 'business_units.csv'
        },
        managers: {
            type: 'string',
            format: 'binary',
            title: 'Managers',
            description: 'managers.csv'
        },
        tickets: {
            type: 'string',
            format: 'binary',
            title: 'Tickets',
            description: 'tickets.csv'
        },
        images: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'binary'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Images',
            description: 'Optional ticket-related images'
        }
    },
    type: 'object',
    required: [
        'business_units',
        'managers',
        'tickets'
    ],
    title: 'Body_ingest_csv_files_api_v1_fire_ingest_post'
} as const;

export const Body_login_api_v1_auth_login_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login_api_v1_auth_login_post'
} as const;

export const Body_upload_file_api_v1_files_upload_postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_upload_file_api_v1_files_upload_post'
} as const;

export const BulkDeleteSchemaSchema = {
    properties: {
        ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Ids'
        }
    },
    type: 'object',
    required: [
        'ids'
    ],
    title: 'BulkDeleteSchema',
    description: 'Schema for bulk deletion requests.'
} as const;

export const BusinessUnitReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        address: {
            type: 'string',
            title: 'Address'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'address'
    ],
    title: 'BusinessUnitRead'
} as const;

export const ClientSegmentSchema = {
    type: 'string',
    enum: [
        'Mass',
        'VIP',
        'Priority'
    ],
    title: 'ClientSegment',
    description: 'Client segments from the FIRE spec.'
} as const;

export const ConversationCreateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title',
            description: 'Conversation title'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id',
            description: 'Owner user ID'
        }
    },
    type: 'object',
    title: 'ConversationCreate',
    description: 'Schema for creating a conversation.'
} as const;

export const ConversationListSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ConversationRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: [
        'items',
        'total'
    ],
    title: 'ConversationList',
    description: 'Schema for listing conversations.'
} as const;

export const ConversationReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title',
            description: 'Conversation title'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        }
    },
    type: 'object',
    required: [
        'created_at',
        'id'
    ],
    title: 'ConversationRead',
    description: 'Schema for reading a conversation (API response).'
} as const;

export const ConversationReadWithMessagesSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title',
            description: 'Conversation title'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        },
        messages: {
            items: {
                $ref: '#/components/schemas/MessageRead'
            },
            type: 'array',
            title: 'Messages'
        }
    },
    type: 'object',
    required: [
        'created_at',
        'id'
    ],
    title: 'ConversationReadWithMessages',
    description: 'Conversation with all messages.'
} as const;

export const ConversationUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'ConversationUpdate',
    description: 'Schema for updating a conversation.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IngestionResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        task_id: {
            type: 'string',
            title: 'Task Id'
        }
    },
    type: 'object',
    required: [
        'message',
        'task_id'
    ],
    title: 'IngestionResponse',
    description: 'Response from starting a background CSV ingestion run.'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title',
            description: 'Item title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Item description'
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'ItemCreate',
    description: 'Schema for creating an item.'
} as const;

export const ItemReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title',
            description: 'Item title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Item description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: [
        'created_at',
        'title',
        'id'
    ],
    title: 'ItemRead',
    description: 'Schema for reading an item (API response).'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ItemUpdate',
    description: 'Schema for updating an item.\n\nAll fields are optional to allow partial updates.'
} as const;

export const ManagerReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        skills: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Skills'
        },
        current_load: {
            type: 'integer',
            title: 'Current Load'
        },
        business_unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Business Unit Id'
        },
        business_unit: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BusinessUnitRead'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'full_name',
        'role',
        'skills',
        'current_load',
        'business_unit_id'
    ],
    title: 'ManagerRead'
} as const;

export const MessageCreateSchema = {
    properties: {
        role: {
            type: 'string',
            enum: [
                'user',
                'assistant',
                'system'
            ],
            title: 'Role',
            description: 'Message role'
        },
        content: {
            type: 'string',
            title: 'Content',
            description: 'Message content'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name',
            description: 'AI model used'
        },
        tokens_used: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tokens Used',
            description: 'Token count'
        }
    },
    type: 'object',
    required: [
        'role',
        'content'
    ],
    title: 'MessageCreate',
    description: 'Schema for creating a message.'
} as const;

export const MessageListSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/MessageReadSimple'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: [
        'items',
        'total'
    ],
    title: 'MessageList',
    description: 'Schema for listing messages.'
} as const;

export const MessageReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        role: {
            type: 'string',
            enum: [
                'user',
                'assistant',
                'system'
            ],
            title: 'Role',
            description: 'Message role'
        },
        content: {
            type: 'string',
            title: 'Content',
            description: 'Message content'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        conversation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conversation Id'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        tokens_used: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tokens Used'
        },
        tool_calls: {
            items: {
                $ref: '#/components/schemas/ToolCallRead'
            },
            type: 'array',
            title: 'Tool Calls'
        }
    },
    type: 'object',
    required: [
        'created_at',
        'role',
        'content',
        'id',
        'conversation_id'
    ],
    title: 'MessageRead',
    description: 'Schema for reading a message (API response).'
} as const;

export const MessageReadSimpleSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        role: {
            type: 'string',
            enum: [
                'user',
                'assistant',
                'system'
            ],
            title: 'Role',
            description: 'Message role'
        },
        content: {
            type: 'string',
            title: 'Content',
            description: 'Message content'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        conversation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conversation Id'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        tokens_used: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tokens Used'
        }
    },
    type: 'object',
    required: [
        'created_at',
        'role',
        'content',
        'id',
        'conversation_id'
    ],
    title: 'MessageReadSimple',
    description: 'Simplified message schema without tool calls.'
} as const;

export const NotificationFeedResponseSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/NotificationRead'
            },
            type: 'array',
            title: 'Items'
        },
        unread_count: {
            type: 'integer',
            title: 'Unread Count',
            description: 'Total number of unread notifications for this user.'
        },
        total_fetched: {
            type: 'integer',
            title: 'Total Fetched',
            description: 'Number of notifications returned in this batch.'
        }
    },
    type: 'object',
    required: [
        'items',
        'unread_count',
        'total_fetched'
    ],
    title: 'NotificationFeedResponse',
    description: 'Feed response returned on page load.\n\nContains the latest N notifications and the running unread count.'
} as const;

export const NotificationMarkAllReadResponseSchema = {
    properties: {
        updated: {
            type: 'integer',
            title: 'Updated',
            description: 'Number of notifications marked as read.'
        }
    },
    type: 'object',
    required: [
        'updated'
    ],
    title: 'NotificationMarkAllReadResponse',
    description: 'Response payload for marking all notifications as read.'
} as const;

export const NotificationReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        payload: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payload'
        },
        is_read: {
            type: 'boolean',
            title: 'Is Read'
        }
    },
    type: 'object',
    required: [
        'created_at',
        'id',
        'user_id',
        'type',
        'title',
        'is_read'
    ],
    title: 'NotificationRead',
    description: 'Schema for reading a notification.'
} as const;

export const Page_ItemRead_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ItemRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total'
        },
        page: {
            type: 'integer',
            minimum: 1,
            title: 'Page'
        },
        size: {
            type: 'integer',
            minimum: 1,
            title: 'Size'
        },
        pages: {
            type: 'integer',
            minimum: 0,
            title: 'Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'size',
        'pages'
    ],
    title: 'Page[ItemRead]'
} as const;

export const Page_NotificationRead_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/NotificationRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total'
        },
        page: {
            type: 'integer',
            minimum: 1,
            title: 'Page'
        },
        size: {
            type: 'integer',
            minimum: 1,
            title: 'Size'
        },
        pages: {
            type: 'integer',
            minimum: 0,
            title: 'Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'size',
        'pages'
    ],
    title: 'Page[NotificationRead]'
} as const;

export const Page_UserRead_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/UserRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total'
        },
        page: {
            type: 'integer',
            minimum: 1,
            title: 'Page'
        },
        size: {
            type: 'integer',
            minimum: 1,
            title: 'Size'
        },
        pages: {
            type: 'integer',
            minimum: 0,
            title: 'Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'size',
        'pages'
    ],
    title: 'Page[UserRead]'
} as const;

export const PaginatedBusinessUnitsSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/BusinessUnitRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        has_next: {
            type: 'boolean',
            title: 'Has Next'
        },
        has_prev: {
            type: 'boolean',
            title: 'Has Prev'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages',
        'has_next',
        'has_prev'
    ],
    title: 'PaginatedBusinessUnits'
} as const;

export const PaginatedManagersSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ManagerRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        has_next: {
            type: 'boolean',
            title: 'Has Next'
        },
        has_prev: {
            type: 'boolean',
            title: 'Has Prev'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages',
        'has_next',
        'has_prev'
    ],
    title: 'PaginatedManagers'
} as const;

export const PaginatedTaskLogsSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/TaskLogRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        has_next: {
            type: 'boolean',
            title: 'Has Next'
        },
        has_prev: {
            type: 'boolean',
            title: 'Has Prev'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages',
        'has_next',
        'has_prev'
    ],
    title: 'PaginatedTaskLogs'
} as const;

export const PaginatedTasksSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/BackgroundTaskRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        has_next: {
            type: 'boolean',
            title: 'Has Next'
        },
        has_prev: {
            type: 'boolean',
            title: 'Has Prev'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages',
        'has_next',
        'has_prev'
    ],
    title: 'PaginatedTasks'
} as const;

export const PaginatedTicketsSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/TicketRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        has_next: {
            type: 'boolean',
            title: 'Has Next'
        },
        has_prev: {
            type: 'boolean',
            title: 'Has Prev'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages',
        'has_next',
        'has_prev'
    ],
    title: 'PaginatedTickets'
} as const;

export const RefreshTokenRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: [
        'refresh_token'
    ],
    title: 'RefreshTokenRequest',
    description: 'Request body for token refresh.'
} as const;

export const RoutingResultReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ticket_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ticket Id'
        },
        assigned_manager_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigned Manager Id'
        },
        business_unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Business Unit Id'
        },
        office_distance_km: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Office Distance Km'
        },
        assignment_method: {
            $ref: '#/components/schemas/AssignmentMethod'
        },
        round_robin_position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Round Robin Position'
        },
        manager_load_at_assignment: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Manager Load At Assignment'
        },
        routing_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Routing Error'
        },
        assigned_manager: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ManagerRead'
                },
                {
                    type: 'null'
                }
            ]
        },
        business_unit: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BusinessUnitRead'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'created_at',
        'id',
        'ticket_id',
        'assignment_method'
    ],
    title: 'RoutingResultRead',
    description: 'Full routing result record — the JOIN view from the spec.'
} as const;

export const TaskActionSchema = {
    type: 'string',
    enum: [
        'START',
        'INFO',
        'WARN',
        'SUCCESS',
        'ERROR',
        'AI_ENRICHED',
        'GEOCODED',
        'ROUTED'
    ],
    title: 'TaskAction'
} as const;

export const TaskLogReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        action: {
            $ref: '#/components/schemas/TaskAction'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    required: [
        'created_at',
        'id',
        'task_id',
        'action',
        'message'
    ],
    title: 'TaskLogRead',
    description: 'Schema for reading a TaskLog.'
} as const;

export const TaskStatusSchema = {
    type: 'string',
    enum: [
        'PENDING',
        'RUNNING',
        'COMPLETED',
        'FAILED'
    ],
    title: 'TaskStatus'
} as const;

export const TicketAIAnalysisReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ticket_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ticket Id'
        },
        ai_type: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TicketType'
                },
                {
                    type: 'null'
                }
            ]
        },
        ai_tone: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TicketTone'
                },
                {
                    type: 'null'
                }
            ]
        },
        ai_priority: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Priority'
        },
        ai_language: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TicketLanguage'
                },
                {
                    type: 'null'
                }
            ]
        },
        ai_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Summary'
        },
        ai_recommendation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Recommendation'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        }
    },
    type: 'object',
    required: [
        'created_at',
        'id',
        'ticket_id'
    ],
    title: 'TicketAIAnalysisRead',
    description: 'AI analysis result — mirrors TicketAnalysis from the notebook.'
} as const;

export const TicketLanguageSchema = {
    type: 'string',
    enum: [
        'KZ',
        'ENG',
        'RU'
    ],
    title: 'TicketLanguage',
    description: 'Detected language values from the FIRE spec §3.1 (default: RU).'
} as const;

export const TicketReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        guid: {
            type: 'string',
            title: 'Guid'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        client_segment: {
            type: 'string',
            title: 'Client Segment'
        },
        client_gender: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Gender'
        },
        client_dob: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Dob'
        },
        client_country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Country'
        },
        client_region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Region'
        },
        client_city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client City'
        },
        client_street: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Street'
        },
        client_building: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Building'
        },
        attachment_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Attachment Path'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        assigned_manager_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigned Manager Id'
        },
        ai_analysis: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TicketAIAnalysisRead'
                },
                {
                    type: 'null'
                }
            ]
        },
        routing_result: {
            anyOf: [
                {
                    $ref: '#/components/schemas/RoutingResultRead'
                },
                {
                    type: 'null'
                }
            ]
        },
        assigned_manager: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ManagerRead'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'created_at',
        'guid',
        'description',
        'client_segment',
        'id'
    ],
    title: 'TicketRead'
} as const;

export const TicketToneSchema = {
    type: 'string',
    enum: [
        'Позитивный',
        'Нейтральный',
        'Негативный'
    ],
    title: 'TicketTone',
    description: 'Sentiment / tone values from the FIRE spec §3.1.'
} as const;

export const TicketTypeSchema = {
    type: 'string',
    enum: [
        'Жалоба',
        'Смена данных',
        'Консультация',
        'Претензия',
        'Неработоспособность приложения',
        'Мошеннические действия',
        'Спам'
    ],
    title: 'TicketType',
    description: 'All 7 ticket classification categories from the FIRE spec §3.1.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token',
        'refresh_token'
    ],
    title: 'Token',
    description: 'OAuth2 token response with refresh token.'
} as const;

export const ToolCallReadSchema = {
    properties: {
        tool_call_id: {
            type: 'string',
            title: 'Tool Call Id',
            description: 'External tool call ID from AI framework'
        },
        tool_name: {
            type: 'string',
            maxLength: 100,
            title: 'Tool Name',
            description: 'Name of the tool called'
        },
        args: {
            additionalProperties: true,
            type: 'object',
            title: 'Args',
            description: 'Tool arguments'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        message_id: {
            type: 'string',
            format: 'uuid',
            title: 'Message Id'
        },
        result: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Result'
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'running',
                'completed',
                'failed'
            ],
            title: 'Status',
            default: 'pending'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        duration_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Ms'
        }
    },
    type: 'object',
    required: [
        'tool_call_id',
        'tool_name',
        'id',
        'message_id',
        'started_at'
    ],
    title: 'ToolCallRead',
    description: 'Schema for reading a tool call (API response).'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            $ref: '#/components/schemas/UserRole',
            default: 'user'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserCreate',
    description: 'Schema for creating a user.'
} as const;

export const UserReadSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            $ref: '#/components/schemas/UserRole',
            default: 'user'
        }
    },
    type: 'object',
    required: [
        'created_at',
        'email',
        'id'
    ],
    title: 'UserRead',
    description: 'Schema for reading a user.'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: [
        'admin',
        'manager',
        'user'
    ],
    title: 'UserRole',
    description: 'User role enumeration for API schemas.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        role: {
            anyOf: [
                {
                    $ref: '#/components/schemas/UserRole'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Schema for updating a user.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
