// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AssignmentMethod
 *
 * How the ticket was routed (for audit traceability).
 */
export type AssignmentMethod = 'geo_nearest' | 'geo_fallback_astana' | 'geo_fallback_almaty' | 'round_robin' | 'skipped_spam' | 'no_eligible_manager';

/**
 * BackgroundTaskRead
 *
 * Schema for reading a BackgroundTask.
 */
export type BackgroundTaskRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Ticket Id
     */
    ticket_id?: string | null;
    /**
     * Task Id
     */
    task_id?: string | null;
    /**
     * Task Name
     */
    task_name: string;
    status: TaskStatus;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Body_ingest_csv_files_api_v1_fire_ingest_post
 */
export type BodyIngestCsvFilesApiV1FireIngestPost = {
    /**
     * Business Units
     *
     * business_units.csv
     */
    business_units: Blob | File;
    /**
     * Managers
     *
     * managers.csv
     */
    managers: Blob | File;
    /**
     * Tickets
     *
     * tickets.csv
     */
    tickets: Blob | File;
    /**
     * Images
     *
     * Optional ticket-related images
     */
    images?: Array<Blob | File> | null;
};

/**
 * Body_login_api_v1_auth_login_post
 */
export type BodyLoginApiV1AuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_upload_file_api_v1_files_upload_post
 */
export type BodyUploadFileApiV1FilesUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BulkDeleteSchema
 *
 * Schema for bulk deletion requests.
 */
export type BulkDeleteSchema = {
    /**
     * Ids
     */
    ids: Array<string>;
};

/**
 * BusinessUnitRead
 */
export type BusinessUnitRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Country
     */
    country?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Address
     */
    address: string;
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Longitude
     */
    longitude?: number | null;
};

/**
 * ClientSegment
 *
 * Client segments from the FIRE spec.
 */
export type ClientSegment = 'Mass' | 'VIP' | 'Priority';

/**
 * ConversationCreate
 *
 * Schema for creating a conversation.
 */
export type ConversationCreate = {
    /**
     * Title
     *
     * Conversation title
     */
    title?: string | null;
    /**
     * User Id
     *
     * Owner user ID
     */
    user_id?: string | null;
};

/**
 * ConversationList
 *
 * Schema for listing conversations.
 */
export type ConversationList = {
    /**
     * Items
     */
    items: Array<ConversationRead>;
    /**
     * Total
     */
    total: number;
};

/**
 * ConversationRead
 *
 * Schema for reading a conversation (API response).
 */
export type ConversationRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Title
     *
     * Conversation title
     */
    title?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Is Archived
     */
    is_archived?: boolean;
};

/**
 * ConversationReadWithMessages
 *
 * Conversation with all messages.
 */
export type ConversationReadWithMessages = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Title
     *
     * Conversation title
     */
    title?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Is Archived
     */
    is_archived?: boolean;
    /**
     * Messages
     */
    messages?: Array<MessageRead>;
};

/**
 * ConversationUpdate
 *
 * Schema for updating a conversation.
 */
export type ConversationUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Is Archived
     */
    is_archived?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IngestionResponse
 *
 * Response from starting a background CSV ingestion run.
 */
export type IngestionResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Task Id
     */
    task_id: string;
};

/**
 * ItemCreate
 *
 * Schema for creating an item.
 */
export type ItemCreate = {
    /**
     * Title
     *
     * Item title
     */
    title: string;
    /**
     * Description
     *
     * Item description
     */
    description?: string | null;
};

/**
 * ItemRead
 *
 * Schema for reading an item (API response).
 */
export type ItemRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Title
     *
     * Item title
     */
    title: string;
    /**
     * Description
     *
     * Item description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * ItemUpdate
 *
 * Schema for updating an item.
 *
 * All fields are optional to allow partial updates.
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ManagerRead
 */
export type ManagerRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Role
     */
    role: string;
    /**
     * Skills
     */
    skills: Array<string>;
    /**
     * Current Load
     */
    current_load: number;
    /**
     * Business Unit Id
     */
    business_unit_id: string;
    business_unit?: BusinessUnitRead | null;
};

/**
 * MessageCreate
 *
 * Schema for creating a message.
 */
export type MessageCreate = {
    /**
     * Role
     *
     * Message role
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     *
     * Message content
     */
    content: string;
    /**
     * Model Name
     *
     * AI model used
     */
    model_name?: string | null;
    /**
     * Tokens Used
     *
     * Token count
     */
    tokens_used?: number | null;
};

/**
 * MessageList
 *
 * Schema for listing messages.
 */
export type MessageList = {
    /**
     * Items
     */
    items: Array<MessageReadSimple>;
    /**
     * Total
     */
    total: number;
};

/**
 * MessageRead
 *
 * Schema for reading a message (API response).
 */
export type MessageRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Role
     *
     * Message role
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     *
     * Message content
     */
    content: string;
    /**
     * Id
     */
    id: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Model Name
     */
    model_name?: string | null;
    /**
     * Tokens Used
     */
    tokens_used?: number | null;
    /**
     * Tool Calls
     */
    tool_calls?: Array<ToolCallRead>;
};

/**
 * MessageReadSimple
 *
 * Simplified message schema without tool calls.
 */
export type MessageReadSimple = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Role
     *
     * Message role
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     *
     * Message content
     */
    content: string;
    /**
     * Id
     */
    id: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Model Name
     */
    model_name?: string | null;
    /**
     * Tokens Used
     */
    tokens_used?: number | null;
};

/**
 * NotificationFeedResponse
 *
 * Feed response returned on page load.
 *
 * Contains the latest N notifications and the running unread count.
 */
export type NotificationFeedResponse = {
    /**
     * Items
     */
    items: Array<NotificationRead>;
    /**
     * Unread Count
     *
     * Total number of unread notifications for this user.
     */
    unread_count: number;
    /**
     * Total Fetched
     *
     * Number of notifications returned in this batch.
     */
    total_fetched: number;
};

/**
 * NotificationMarkAllReadResponse
 *
 * Response payload for marking all notifications as read.
 */
export type NotificationMarkAllReadResponse = {
    /**
     * Updated
     *
     * Number of notifications marked as read.
     */
    updated: number;
};

/**
 * NotificationRead
 *
 * Schema for reading a notification.
 */
export type NotificationRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    } | null;
    /**
     * Is Read
     */
    is_read: boolean;
};

/**
 * Page[ItemRead]
 */
export type PageItemRead = {
    /**
     * Items
     */
    items: Array<ItemRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * Page[NotificationRead]
 */
export type PageNotificationRead = {
    /**
     * Items
     */
    items: Array<NotificationRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * Page[UserRead]
 */
export type PageUserRead = {
    /**
     * Items
     */
    items: Array<UserRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PaginatedBusinessUnits
 */
export type PaginatedBusinessUnits = {
    /**
     * Items
     */
    items: Array<BusinessUnitRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * PaginatedManagers
 */
export type PaginatedManagers = {
    /**
     * Items
     */
    items: Array<ManagerRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * PaginatedTaskLogs
 */
export type PaginatedTaskLogs = {
    /**
     * Items
     */
    items: Array<TaskLogRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * PaginatedTasks
 */
export type PaginatedTasks = {
    /**
     * Items
     */
    items: Array<BackgroundTaskRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * PaginatedTickets
 */
export type PaginatedTickets = {
    /**
     * Items
     */
    items: Array<TicketRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * RefreshTokenRequest
 *
 * Request body for token refresh.
 */
export type RefreshTokenRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RoutingResultRead
 *
 * Full routing result record — the JOIN view from the spec.
 */
export type RoutingResultRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Ticket Id
     */
    ticket_id: string;
    /**
     * Assigned Manager Id
     */
    assigned_manager_id?: string | null;
    /**
     * Business Unit Id
     */
    business_unit_id?: string | null;
    /**
     * Office Distance Km
     */
    office_distance_km?: number | null;
    assignment_method: AssignmentMethod;
    /**
     * Round Robin Position
     */
    round_robin_position?: number | null;
    /**
     * Manager Load At Assignment
     */
    manager_load_at_assignment?: number | null;
    /**
     * Routing Error
     */
    routing_error?: string | null;
    assigned_manager?: ManagerRead | null;
    business_unit?: BusinessUnitRead | null;
};

/**
 * TaskAction
 */
export type TaskAction = 'START' | 'INFO' | 'WARN' | 'SUCCESS' | 'ERROR' | 'AI_ENRICHED' | 'GEOCODED' | 'ROUTED';

/**
 * TaskLogRead
 *
 * Schema for reading a TaskLog.
 */
export type TaskLogRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Task Id
     */
    task_id: string;
    action: TaskAction;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * TaskStatus
 */
export type TaskStatus = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';

/**
 * TicketAIAnalysisRead
 *
 * AI analysis result — mirrors TicketAnalysis from the notebook.
 */
export type TicketAiAnalysisRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Ticket Id
     */
    ticket_id: string;
    ai_type?: TicketType | null;
    ai_tone?: TicketTone | null;
    /**
     * Ai Priority
     */
    ai_priority?: number | null;
    ai_language?: TicketLanguage | null;
    /**
     * Ai Summary
     */
    ai_summary?: string | null;
    /**
     * Ai Recommendation
     */
    ai_recommendation?: string | null;
    /**
     * Model Name
     */
    model_name?: string | null;
};

/**
 * TicketLanguage
 *
 * Detected language values from the FIRE spec §3.1 (default: RU).
 */
export type TicketLanguage = 'KZ' | 'ENG' | 'RU';

/**
 * TicketRead
 */
export type TicketRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Guid
     */
    guid: string;
    /**
     * Description
     */
    description: string;
    /**
     * Client Segment
     */
    client_segment: string;
    /**
     * Client Gender
     */
    client_gender?: string | null;
    /**
     * Client Dob
     */
    client_dob?: string | null;
    /**
     * Client Country
     */
    client_country?: string | null;
    /**
     * Client Region
     */
    client_region?: string | null;
    /**
     * Client City
     */
    client_city?: string | null;
    /**
     * Client Street
     */
    client_street?: string | null;
    /**
     * Client Building
     */
    client_building?: string | null;
    /**
     * Attachment Path
     */
    attachment_path?: string | null;
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Longitude
     */
    longitude?: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Assigned Manager Id
     */
    assigned_manager_id?: string | null;
    ai_analysis?: TicketAiAnalysisRead | null;
    routing_result?: RoutingResultRead | null;
    assigned_manager?: ManagerRead | null;
};

/**
 * TicketTone
 *
 * Sentiment / tone values from the FIRE spec §3.1.
 */
export type TicketTone = 'Позитивный' | 'Нейтральный' | 'Негативный';

/**
 * TicketType
 *
 * All 7 ticket classification categories from the FIRE spec §3.1.
 */
export type TicketType = 'Жалоба' | 'Смена данных' | 'Консультация' | 'Претензия' | 'Неработоспособность приложения' | 'Мошеннические действия' | 'Спам';

/**
 * Token
 *
 * OAuth2 token response with refresh token.
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * ToolCallRead
 *
 * Schema for reading a tool call (API response).
 */
export type ToolCallRead = {
    /**
     * Tool Call Id
     *
     * External tool call ID from AI framework
     */
    tool_call_id: string;
    /**
     * Tool Name
     *
     * Name of the tool called
     */
    tool_name: string;
    /**
     * Args
     *
     * Tool arguments
     */
    args?: {
        [key: string]: unknown;
    };
    /**
     * Id
     */
    id: string;
    /**
     * Message Id
     */
    message_id: string;
    /**
     * Result
     */
    result?: string | null;
    /**
     * Status
     */
    status?: 'pending' | 'running' | 'completed' | 'failed';
    /**
     * Started At
     */
    started_at: string;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Duration Ms
     */
    duration_ms?: number | null;
};

/**
 * UserCreate
 *
 * Schema for creating a user.
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
};

/**
 * UserRead
 *
 * Schema for reading a user.
 */
export type UserRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    role?: UserRole;
};

/**
 * UserRole
 *
 * User role enumeration for API schemas.
 */
export type UserRole = 'admin' | 'manager' | 'user';

/**
 * UserUpdate
 *
 * Schema for updating a user.
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    role?: UserRole | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckApiV1HealthGetResponses = {
    /**
     * Response Health Check Api V1 Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckApiV1HealthGetResponse = HealthCheckApiV1HealthGetResponses[keyof HealthCheckApiV1HealthGetResponses];

export type LivenessProbeApiV1HealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type LivenessProbeApiV1HealthLiveGetResponses = {
    /**
     * Response Liveness Probe Api V1 Health Live Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type LivenessProbeApiV1HealthLiveGetResponse = LivenessProbeApiV1HealthLiveGetResponses[keyof LivenessProbeApiV1HealthLiveGetResponses];

export type ReadinessProbeApiV1HealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type ReadinessProbeApiV1HealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadinessCheckApiV1ReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ready';
};

export type ReadinessCheckApiV1ReadyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiV1AuthLoginPostData = {
    body: BodyLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type RegisterApiV1AuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterApiV1AuthRegisterPostResponse = RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type RefreshTokenApiV1AuthRefreshPostData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshTokenApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshTokenApiV1AuthRefreshPostError = RefreshTokenApiV1AuthRefreshPostErrors[keyof RefreshTokenApiV1AuthRefreshPostErrors];

export type RefreshTokenApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type RefreshTokenApiV1AuthRefreshPostResponse = RefreshTokenApiV1AuthRefreshPostResponses[keyof RefreshTokenApiV1AuthRefreshPostResponses];

export type GetCurrentUserInfoApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetCurrentUserInfoApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetCurrentUserInfoApiV1AuthMeGetResponse = GetCurrentUserInfoApiV1AuthMeGetResponses[keyof GetCurrentUserInfoApiV1AuthMeGetResponses];

export type ReadCurrentUserApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ReadCurrentUserApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadCurrentUserApiV1UsersMeGetResponse = ReadCurrentUserApiV1UsersMeGetResponses[keyof ReadCurrentUserApiV1UsersMeGetResponses];

export type UpdateCurrentUserApiV1UsersMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateCurrentUserApiV1UsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserApiV1UsersMePatchError = UpdateCurrentUserApiV1UsersMePatchErrors[keyof UpdateCurrentUserApiV1UsersMePatchErrors];

export type UpdateCurrentUserApiV1UsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateCurrentUserApiV1UsersMePatchResponse = UpdateCurrentUserApiV1UsersMePatchResponses[keyof UpdateCurrentUserApiV1UsersMePatchResponses];

export type ReadUsersApiV1UsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type ReadUsersApiV1UsersGetResponses = {
    /**
     * Successful Response
     */
    200: PageUserRead;
};

export type ReadUsersApiV1UsersGetResponse = ReadUsersApiV1UsersGetResponses[keyof ReadUsersApiV1UsersGetResponses];

export type DeleteUserByIdApiV1UsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteUserByIdApiV1UsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserByIdApiV1UsersUserIdDeleteError = DeleteUserByIdApiV1UsersUserIdDeleteErrors[keyof DeleteUserByIdApiV1UsersUserIdDeleteErrors];

export type DeleteUserByIdApiV1UsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserByIdApiV1UsersUserIdDeleteResponse = DeleteUserByIdApiV1UsersUserIdDeleteResponses[keyof DeleteUserByIdApiV1UsersUserIdDeleteResponses];

export type ReadUserApiV1UsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ReadUserApiV1UsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserApiV1UsersUserIdGetError = ReadUserApiV1UsersUserIdGetErrors[keyof ReadUserApiV1UsersUserIdGetErrors];

export type ReadUserApiV1UsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadUserApiV1UsersUserIdGetResponse = ReadUserApiV1UsersUserIdGetResponses[keyof ReadUserApiV1UsersUserIdGetResponses];

export type UpdateUserByIdApiV1UsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UpdateUserByIdApiV1UsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserByIdApiV1UsersUserIdPatchError = UpdateUserByIdApiV1UsersUserIdPatchErrors[keyof UpdateUserByIdApiV1UsersUserIdPatchErrors];

export type UpdateUserByIdApiV1UsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserByIdApiV1UsersUserIdPatchResponse = UpdateUserByIdApiV1UsersUserIdPatchResponses[keyof UpdateUserByIdApiV1UsersUserIdPatchResponses];

export type ListItemsApiV1ItemsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/items';
};

export type ListItemsApiV1ItemsGetResponses = {
    /**
     * Successful Response
     */
    200: PageItemRead;
};

export type ListItemsApiV1ItemsGetResponse = ListItemsApiV1ItemsGetResponses[keyof ListItemsApiV1ItemsGetResponses];

export type CreateItemApiV1ItemsPostData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items';
};

export type CreateItemApiV1ItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemApiV1ItemsPostError = CreateItemApiV1ItemsPostErrors[keyof CreateItemApiV1ItemsPostErrors];

export type CreateItemApiV1ItemsPostResponses = {
    /**
     * Successful Response
     */
    201: ItemRead;
};

export type CreateItemApiV1ItemsPostResponse = CreateItemApiV1ItemsPostResponses[keyof CreateItemApiV1ItemsPostResponses];

export type DeleteItemApiV1ItemsItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/v1/items/{item_id}';
};

export type DeleteItemApiV1ItemsItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemApiV1ItemsItemIdDeleteError = DeleteItemApiV1ItemsItemIdDeleteErrors[keyof DeleteItemApiV1ItemsItemIdDeleteErrors];

export type DeleteItemApiV1ItemsItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteItemApiV1ItemsItemIdDeleteResponse = DeleteItemApiV1ItemsItemIdDeleteResponses[keyof DeleteItemApiV1ItemsItemIdDeleteResponses];

export type GetItemApiV1ItemsItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/v1/items/{item_id}';
};

export type GetItemApiV1ItemsItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemApiV1ItemsItemIdGetError = GetItemApiV1ItemsItemIdGetErrors[keyof GetItemApiV1ItemsItemIdGetErrors];

export type GetItemApiV1ItemsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ItemRead;
};

export type GetItemApiV1ItemsItemIdGetResponse = GetItemApiV1ItemsItemIdGetResponses[keyof GetItemApiV1ItemsItemIdGetResponses];

export type UpdateItemApiV1ItemsItemIdPatchData = {
    body: ItemUpdate;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/v1/items/{item_id}';
};

export type UpdateItemApiV1ItemsItemIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemApiV1ItemsItemIdPatchError = UpdateItemApiV1ItemsItemIdPatchErrors[keyof UpdateItemApiV1ItemsItemIdPatchErrors];

export type UpdateItemApiV1ItemsItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ItemRead;
};

export type UpdateItemApiV1ItemsItemIdPatchResponse = UpdateItemApiV1ItemsItemIdPatchResponses[keyof UpdateItemApiV1ItemsItemIdPatchResponses];

export type UploadFileApiV1FilesUploadPostData = {
    body: BodyUploadFileApiV1FilesUploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/files/upload';
};

export type UploadFileApiV1FilesUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileApiV1FilesUploadPostError = UploadFileApiV1FilesUploadPostErrors[keyof UploadFileApiV1FilesUploadPostErrors];

export type UploadFileApiV1FilesUploadPostResponses = {
    /**
     * Response Upload File Api V1 Files Upload Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type UploadFileApiV1FilesUploadPostResponse = UploadFileApiV1FilesUploadPostResponses[keyof UploadFileApiV1FilesUploadPostResponses];

export type DeleteFileApiV1FilesFilePathDeleteData = {
    body?: never;
    path: {
        /**
         * File Path
         */
        file_path: string;
    };
    query?: never;
    url: '/api/v1/files/{file_path}';
};

export type DeleteFileApiV1FilesFilePathDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFileApiV1FilesFilePathDeleteError = DeleteFileApiV1FilesFilePathDeleteErrors[keyof DeleteFileApiV1FilesFilePathDeleteErrors];

export type DeleteFileApiV1FilesFilePathDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteFileApiV1FilesFilePathDeleteResponse = DeleteFileApiV1FilesFilePathDeleteResponses[keyof DeleteFileApiV1FilesFilePathDeleteResponses];

export type ListConversationsApiV1ConversationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         *
         * Number of conversations to skip
         */
        skip?: number;
        /**
         * Limit
         *
         * Maximum conversations to return
         */
        limit?: number;
        /**
         * Include Archived
         *
         * Include archived conversations
         */
        include_archived?: boolean;
    };
    url: '/api/v1/conversations';
};

export type ListConversationsApiV1ConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConversationsApiV1ConversationsGetError = ListConversationsApiV1ConversationsGetErrors[keyof ListConversationsApiV1ConversationsGetErrors];

export type ListConversationsApiV1ConversationsGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationList;
};

export type ListConversationsApiV1ConversationsGetResponse = ListConversationsApiV1ConversationsGetResponses[keyof ListConversationsApiV1ConversationsGetResponses];

export type CreateConversationApiV1ConversationsPostData = {
    /**
     * Data
     */
    body?: ConversationCreate | null;
    path?: never;
    query?: never;
    url: '/api/v1/conversations';
};

export type CreateConversationApiV1ConversationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationApiV1ConversationsPostError = CreateConversationApiV1ConversationsPostErrors[keyof CreateConversationApiV1ConversationsPostErrors];

export type CreateConversationApiV1ConversationsPostResponses = {
    /**
     * Successful Response
     */
    201: ConversationRead;
};

export type CreateConversationApiV1ConversationsPostResponse = CreateConversationApiV1ConversationsPostResponses[keyof CreateConversationApiV1ConversationsPostResponses];

export type DeleteConversationApiV1ConversationsConversationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}';
};

export type DeleteConversationApiV1ConversationsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationApiV1ConversationsConversationIdDeleteError = DeleteConversationApiV1ConversationsConversationIdDeleteErrors[keyof DeleteConversationApiV1ConversationsConversationIdDeleteErrors];

export type DeleteConversationApiV1ConversationsConversationIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConversationApiV1ConversationsConversationIdDeleteResponse = DeleteConversationApiV1ConversationsConversationIdDeleteResponses[keyof DeleteConversationApiV1ConversationsConversationIdDeleteResponses];

export type GetConversationApiV1ConversationsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}';
};

export type GetConversationApiV1ConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiV1ConversationsConversationIdGetError = GetConversationApiV1ConversationsConversationIdGetErrors[keyof GetConversationApiV1ConversationsConversationIdGetErrors];

export type GetConversationApiV1ConversationsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationReadWithMessages;
};

export type GetConversationApiV1ConversationsConversationIdGetResponse = GetConversationApiV1ConversationsConversationIdGetResponses[keyof GetConversationApiV1ConversationsConversationIdGetResponses];

export type UpdateConversationApiV1ConversationsConversationIdPatchData = {
    body: ConversationUpdate;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}';
};

export type UpdateConversationApiV1ConversationsConversationIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConversationApiV1ConversationsConversationIdPatchError = UpdateConversationApiV1ConversationsConversationIdPatchErrors[keyof UpdateConversationApiV1ConversationsConversationIdPatchErrors];

export type UpdateConversationApiV1ConversationsConversationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ConversationRead;
};

export type UpdateConversationApiV1ConversationsConversationIdPatchResponse = UpdateConversationApiV1ConversationsConversationIdPatchResponses[keyof UpdateConversationApiV1ConversationsConversationIdPatchResponses];

export type ArchiveConversationApiV1ConversationsConversationIdArchivePostData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}/archive';
};

export type ArchiveConversationApiV1ConversationsConversationIdArchivePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveConversationApiV1ConversationsConversationIdArchivePostError = ArchiveConversationApiV1ConversationsConversationIdArchivePostErrors[keyof ArchiveConversationApiV1ConversationsConversationIdArchivePostErrors];

export type ArchiveConversationApiV1ConversationsConversationIdArchivePostResponses = {
    /**
     * Successful Response
     */
    200: ConversationRead;
};

export type ArchiveConversationApiV1ConversationsConversationIdArchivePostResponse = ArchiveConversationApiV1ConversationsConversationIdArchivePostResponses[keyof ArchiveConversationApiV1ConversationsConversationIdArchivePostResponses];

export type ListMessagesApiV1ConversationsConversationIdMessagesGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/conversations/{conversation_id}/messages';
};

export type ListMessagesApiV1ConversationsConversationIdMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMessagesApiV1ConversationsConversationIdMessagesGetError = ListMessagesApiV1ConversationsConversationIdMessagesGetErrors[keyof ListMessagesApiV1ConversationsConversationIdMessagesGetErrors];

export type ListMessagesApiV1ConversationsConversationIdMessagesGetResponses = {
    /**
     * Successful Response
     */
    200: MessageList;
};

export type ListMessagesApiV1ConversationsConversationIdMessagesGetResponse = ListMessagesApiV1ConversationsConversationIdMessagesGetResponses[keyof ListMessagesApiV1ConversationsConversationIdMessagesGetResponses];

export type AddMessageApiV1ConversationsConversationIdMessagesPostData = {
    body: MessageCreate;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}/messages';
};

export type AddMessageApiV1ConversationsConversationIdMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMessageApiV1ConversationsConversationIdMessagesPostError = AddMessageApiV1ConversationsConversationIdMessagesPostErrors[keyof AddMessageApiV1ConversationsConversationIdMessagesPostErrors];

export type AddMessageApiV1ConversationsConversationIdMessagesPostResponses = {
    /**
     * Successful Response
     */
    201: MessageRead;
};

export type AddMessageApiV1ConversationsConversationIdMessagesPostResponse = AddMessageApiV1ConversationsConversationIdMessagesPostResponses[keyof AddMessageApiV1ConversationsConversationIdMessagesPostResponses];

export type ListNotificationsApiV1NotificationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications';
};

export type ListNotificationsApiV1NotificationsGetResponses = {
    /**
     * Successful Response
     */
    200: PageNotificationRead;
};

export type ListNotificationsApiV1NotificationsGetResponse = ListNotificationsApiV1NotificationsGetResponses[keyof ListNotificationsApiV1NotificationsGetResponses];

export type GetNotificationFeedApiV1NotificationsFeedGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         *
         * Max notifications to return.
         */
        limit?: number;
    };
    url: '/api/v1/notifications/feed';
};

export type GetNotificationFeedApiV1NotificationsFeedGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNotificationFeedApiV1NotificationsFeedGetError = GetNotificationFeedApiV1NotificationsFeedGetErrors[keyof GetNotificationFeedApiV1NotificationsFeedGetErrors];

export type GetNotificationFeedApiV1NotificationsFeedGetResponses = {
    /**
     * Successful Response
     */
    200: NotificationFeedResponse;
};

export type GetNotificationFeedApiV1NotificationsFeedGetResponse = GetNotificationFeedApiV1NotificationsFeedGetResponses[keyof GetNotificationFeedApiV1NotificationsFeedGetResponses];

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPostData = {
    body?: never;
    path: {
        /**
         * Notification Id
         */
        notification_id: string;
    };
    query?: never;
    url: '/api/v1/notifications/{notification_id}/read';
};

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPostError = MarkNotificationReadApiV1NotificationsNotificationIdReadPostErrors[keyof MarkNotificationReadApiV1NotificationsNotificationIdReadPostErrors];

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPostResponses = {
    /**
     * Successful Response
     */
    200: NotificationRead;
};

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPostResponse = MarkNotificationReadApiV1NotificationsNotificationIdReadPostResponses[keyof MarkNotificationReadApiV1NotificationsNotificationIdReadPostResponses];

export type MarkAllNotificationsReadApiV1NotificationsReadAllPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/read-all';
};

export type MarkAllNotificationsReadApiV1NotificationsReadAllPostResponses = {
    /**
     * Successful Response
     */
    200: NotificationMarkAllReadResponse;
};

export type MarkAllNotificationsReadApiV1NotificationsReadAllPostResponse = MarkAllNotificationsReadApiV1NotificationsReadAllPostResponses[keyof MarkAllNotificationsReadApiV1NotificationsReadAllPostResponses];

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Notification Id
         */
        notification_id: string;
    };
    query?: never;
    url: '/api/v1/notifications/{notification_id}';
};

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteError = DeleteNotificationApiV1NotificationsNotificationIdDeleteErrors[keyof DeleteNotificationApiV1NotificationsNotificationIdDeleteErrors];

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteResponse = DeleteNotificationApiV1NotificationsNotificationIdDeleteResponses[keyof DeleteNotificationApiV1NotificationsNotificationIdDeleteResponses];

export type IngestCsvFilesApiV1FireIngestPostData = {
    body: BodyIngestCsvFilesApiV1FireIngestPost;
    path?: never;
    query?: never;
    url: '/api/v1/fire/ingest';
};

export type IngestCsvFilesApiV1FireIngestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestCsvFilesApiV1FireIngestPostError = IngestCsvFilesApiV1FireIngestPostErrors[keyof IngestCsvFilesApiV1FireIngestPostErrors];

export type IngestCsvFilesApiV1FireIngestPostResponses = {
    /**
     * Successful Response
     */
    201: IngestionResponse;
};

export type IngestCsvFilesApiV1FireIngestPostResponse = IngestCsvFilesApiV1FireIngestPostResponses[keyof IngestCsvFilesApiV1FireIngestPostResponses];

export type BulkDeleteTasksApiV1FireTasksDeleteData = {
    body: BulkDeleteSchema;
    path?: never;
    query?: never;
    url: '/api/v1/fire/tasks';
};

export type BulkDeleteTasksApiV1FireTasksDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkDeleteTasksApiV1FireTasksDeleteError = BulkDeleteTasksApiV1FireTasksDeleteErrors[keyof BulkDeleteTasksApiV1FireTasksDeleteErrors];

export type BulkDeleteTasksApiV1FireTasksDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTasksApiV1FireTasksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: TaskStatus | null;
        /**
         * Task Name
         */
        task_name?: string | null;
        /**
         * Ticket Id
         */
        ticket_id?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string;
        /**
         * Sort Dir
         */
        sort_dir?: string;
    };
    url: '/api/v1/fire/tasks';
};

export type ListTasksApiV1FireTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTasksApiV1FireTasksGetError = ListTasksApiV1FireTasksGetErrors[keyof ListTasksApiV1FireTasksGetErrors];

export type ListTasksApiV1FireTasksGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedTasks;
};

export type ListTasksApiV1FireTasksGetResponse = ListTasksApiV1FireTasksGetResponses[keyof ListTasksApiV1FireTasksGetResponses];

export type GetTaskApiV1FireTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/fire/tasks/{task_id}';
};

export type GetTaskApiV1FireTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskApiV1FireTasksTaskIdGetError = GetTaskApiV1FireTasksTaskIdGetErrors[keyof GetTaskApiV1FireTasksTaskIdGetErrors];

export type GetTaskApiV1FireTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: BackgroundTaskRead;
};

export type GetTaskApiV1FireTasksTaskIdGetResponse = GetTaskApiV1FireTasksTaskIdGetResponses[keyof GetTaskApiV1FireTasksTaskIdGetResponses];

export type GetTicketTasksApiV1FireTicketsTicketIdTasksGetData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/fire/tickets/{ticket_id}/tasks';
};

export type GetTicketTasksApiV1FireTicketsTicketIdTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketTasksApiV1FireTicketsTicketIdTasksGetError = GetTicketTasksApiV1FireTicketsTicketIdTasksGetErrors[keyof GetTicketTasksApiV1FireTicketsTicketIdTasksGetErrors];

export type GetTicketTasksApiV1FireTicketsTicketIdTasksGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedTasks;
};

export type GetTicketTasksApiV1FireTicketsTicketIdTasksGetResponse = GetTicketTasksApiV1FireTicketsTicketIdTasksGetResponses[keyof GetTicketTasksApiV1FireTicketsTicketIdTasksGetResponses];

export type GetTaskLogsApiV1FireTasksTaskIdLogsGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * Action
         */
        action?: TaskAction | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/fire/tasks/{task_id}/logs';
};

export type GetTaskLogsApiV1FireTasksTaskIdLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskLogsApiV1FireTasksTaskIdLogsGetError = GetTaskLogsApiV1FireTasksTaskIdLogsGetErrors[keyof GetTaskLogsApiV1FireTasksTaskIdLogsGetErrors];

export type GetTaskLogsApiV1FireTasksTaskIdLogsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedTaskLogs;
};

export type GetTaskLogsApiV1FireTasksTaskIdLogsGetResponse = GetTaskLogsApiV1FireTasksTaskIdLogsGetResponses[keyof GetTaskLogsApiV1FireTasksTaskIdLogsGetResponses];

export type ClearAllLogsApiV1FireLogsDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/fire/logs';
};

export type ClearAllLogsApiV1FireLogsDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListAllLogsApiV1FireLogsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Task Id
         */
        task_id?: string | null;
        /**
         * Action
         */
        action?: TaskAction | null;
        /**
         * Message Query
         */
        message_query?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string;
        /**
         * Sort Dir
         */
        sort_dir?: string;
    };
    url: '/api/v1/fire/logs';
};

export type ListAllLogsApiV1FireLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAllLogsApiV1FireLogsGetError = ListAllLogsApiV1FireLogsGetErrors[keyof ListAllLogsApiV1FireLogsGetErrors];

export type ListAllLogsApiV1FireLogsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedTaskLogs;
};

export type ListAllLogsApiV1FireLogsGetResponse = ListAllLogsApiV1FireLogsGetResponses[keyof ListAllLogsApiV1FireLogsGetResponses];

export type ClearIngestionStorageApiV1FireStorageDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/fire/storage';
};

export type ClearIngestionStorageApiV1FireStorageDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResetAllFireDataApiV1FireResetAllDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/fire/reset-all';
};

export type ResetAllFireDataApiV1FireResetAllDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BulkDeleteTicketsApiV1FireTicketsDeleteData = {
    body: BulkDeleteSchema;
    path?: never;
    query?: never;
    url: '/api/v1/fire/tickets';
};

export type BulkDeleteTicketsApiV1FireTicketsDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkDeleteTicketsApiV1FireTicketsDeleteError = BulkDeleteTicketsApiV1FireTicketsDeleteErrors[keyof BulkDeleteTicketsApiV1FireTicketsDeleteErrors];

export type BulkDeleteTicketsApiV1FireTicketsDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTicketsApiV1FireTicketsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Ids
         */
        ids?: Array<string> | null;
        /**
         * Client Segment
         */
        client_segment?: ClientSegment | null;
        /**
         * Assigned Manager Id
         */
        assigned_manager_id?: string | null;
        /**
         * Client City
         */
        client_city?: string | null;
        /**
         * Ai Type
         */
        ai_type?: TicketType | null;
        /**
         * Ai Tone
         */
        ai_tone?: TicketTone | null;
        /**
         * Ai Priority Min
         */
        ai_priority_min?: number | null;
        /**
         * Ai Priority Max
         */
        ai_priority_max?: number | null;
        /**
         * Ai Language
         */
        ai_language?: TicketLanguage | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string;
        /**
         * Sort Dir
         */
        sort_dir?: string;
    };
    url: '/api/v1/fire/tickets';
};

export type ListTicketsApiV1FireTicketsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTicketsApiV1FireTicketsGetError = ListTicketsApiV1FireTicketsGetErrors[keyof ListTicketsApiV1FireTicketsGetErrors];

export type ListTicketsApiV1FireTicketsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedTickets;
};

export type ListTicketsApiV1FireTicketsGetResponse = ListTicketsApiV1FireTicketsGetResponses[keyof ListTicketsApiV1FireTicketsGetResponses];

export type BulkDeleteManagersApiV1FireManagersDeleteData = {
    body: BulkDeleteSchema;
    path?: never;
    query?: never;
    url: '/api/v1/fire/managers';
};

export type BulkDeleteManagersApiV1FireManagersDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkDeleteManagersApiV1FireManagersDeleteError = BulkDeleteManagersApiV1FireManagersDeleteErrors[keyof BulkDeleteManagersApiV1FireManagersDeleteErrors];

export type BulkDeleteManagersApiV1FireManagersDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListManagersApiV1FireManagersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Ids
         */
        ids?: Array<string> | null;
        /**
         * Role
         */
        role?: string | null;
        /**
         * Business Unit Id
         */
        business_unit_id?: string | null;
        /**
         * Current Load Min
         */
        current_load_min?: number | null;
        /**
         * Current Load Max
         */
        current_load_max?: number | null;
        /**
         * Skill
         */
        skill?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string;
        /**
         * Sort Dir
         */
        sort_dir?: string;
    };
    url: '/api/v1/fire/managers';
};

export type ListManagersApiV1FireManagersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListManagersApiV1FireManagersGetError = ListManagersApiV1FireManagersGetErrors[keyof ListManagersApiV1FireManagersGetErrors];

export type ListManagersApiV1FireManagersGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedManagers;
};

export type ListManagersApiV1FireManagersGetResponse = ListManagersApiV1FireManagersGetResponses[keyof ListManagersApiV1FireManagersGetResponses];

export type BulkDeleteBusinessUnitsApiV1FireBusinessUnitsDeleteData = {
    body: BulkDeleteSchema;
    path?: never;
    query?: never;
    url: '/api/v1/fire/business-units';
};

export type BulkDeleteBusinessUnitsApiV1FireBusinessUnitsDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkDeleteBusinessUnitsApiV1FireBusinessUnitsDeleteError = BulkDeleteBusinessUnitsApiV1FireBusinessUnitsDeleteErrors[keyof BulkDeleteBusinessUnitsApiV1FireBusinessUnitsDeleteErrors];

export type BulkDeleteBusinessUnitsApiV1FireBusinessUnitsDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListBusinessUnitsApiV1FireBusinessUnitsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Ids
         */
        ids?: Array<string> | null;
        /**
         * City
         */
        city?: string | null;
        /**
         * Country
         */
        country?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Sort By
         */
        sort_by?: string;
        /**
         * Sort Dir
         */
        sort_dir?: string;
    };
    url: '/api/v1/fire/business-units';
};

export type ListBusinessUnitsApiV1FireBusinessUnitsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBusinessUnitsApiV1FireBusinessUnitsGetError = ListBusinessUnitsApiV1FireBusinessUnitsGetErrors[keyof ListBusinessUnitsApiV1FireBusinessUnitsGetErrors];

export type ListBusinessUnitsApiV1FireBusinessUnitsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedBusinessUnits;
};

export type ListBusinessUnitsApiV1FireBusinessUnitsGetResponse = ListBusinessUnitsApiV1FireBusinessUnitsGetResponses[keyof ListBusinessUnitsApiV1FireBusinessUnitsGetResponses];

export type ChatStreamingApiV1ChatPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat';
};

export type ChatStreamingApiV1ChatPostResponses = {
    /**
     * Response Chat Streaming Api V1 Chat Post
     *
     * Successful Response
     */
    200: unknown;
};

export type GetFileMediaFilePathGetData = {
    body?: never;
    path: {
        /**
         * File Path
         */
        file_path: string;
    };
    query?: never;
    url: '/media/{file_path}';
};

export type GetFileMediaFilePathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFileMediaFilePathGetError = GetFileMediaFilePathGetErrors[keyof GetFileMediaFilePathGetErrors];

export type GetFileMediaFilePathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
